### ISSUE TITLE
Todo for recovery

### ISSUE THREAD

**Issue by willirath** [geomar-od-lagrange/2022_eDNA_KielBight_Buoys#1]
- [ ] Positions in decimal minutes
- [ ] Drift prediciton for 30 minutes (use last 2 or 3 positions)
- [x] caching of CSV data?
